name: 'Smith & Ratciffe Ancestry'
favicon: null
layout_spectrum: 0.75106
typography_spectrum: 0.26595
title: The Apple Family History
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#604c43'
    - '#fefff9'
    - '#7d7d7d'
    - '#221715'
    - '#bfb0ab'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
