title: The Apple Family History
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.5
  rhythmicContrast: 1
  brandColors:
    - '#604c43'
    - '#fefff9'
    - '#7d7d7d'
    - '#221715'
    - '#bfb0ab'
  lightness: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'Smith & Ratciffe Ancestry'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.07234043
layout_spectrum: 0.9404255
